# The docker compose file is used to start and stop your app's Docker containers.
version: "3.7"

services:
  # The app proxy is always needed and tells Umbrel how to route traffic to your app.
  app_proxy:
    environment:
      # <app-id>_<web-container-name>_1
      # e.g. 'btc-rpc-explorer_web_1'
      # Note that the '_1' at the end is needed
      APP_HOST: pixina_app_1
      # The port your app's web server is listening on
      APP_PORT: 3000
  
  app:
    # Note: always use the image digest to ensure reproducability across installations
    image: ghcr.io/sharknoon/pixina:latest@sha256:b71eb3a893af30162f3a00816c664503d74b5934e995c2dfbe84d5f5a0c1a163
    restart: on-failure
    stop_grace_period: 1m
    # ports:
      # You do not need to expose the port that your app's web server is listening on if you're using the app_proxy service.
      # This is handled by the APP_HOST and APP_PORT environment variables in the service above.
      #
      # If you need to expose additional ports, you can do so like this, replacing <port> with the port number:
      #- <port>:<port>
    # volumes:
      # Uncomment to mount your data directories inside
      # the Docker container for storing persistent data
      # - ${APP_DATA_DIR}/foo:/foo
      # - ${APP_DATA_DIR}/bar:/bar
      #
      # Uncomment to mount LND's data directory as read-only
      # inside the Docker container at path /lnd
      # - ${APP_LIGHTNING_NODE_DATA_DIR}:/lnd:ro
      #
      # Uncomment to mount Bitcoin Core's data directory as
      # read-only inside the Docker container at path /bitcoin
      # - ${APP_BITCOIN_DATA_DIR}:/bitcoin:ro
    environment:
      # Pass any environment variables to your app for configuration in the form:
      # VARIABLE_NAME: value
      PIXINA_PIXELHOBBY_TILE_ID: 35007450218648
      PIXINA_API_URL: http://${DEVICE_DOMAIN_NAME}/api/v1/progress
      #
      # Here are all the Umbrel provided variables that you can pass through to
      # your app
      # System level environment variables
      # $DEVICE_HOSTNAME - Umbrel server device hostname (e.g. "umbrel")
      # $DEVICE_DOMAIN_NAME - A .local domain name for the Umbrel server (e.g. "umbrel.local")
      #
      # Tor proxy environment variables
      # $TOR_PROXY_IP - Local IP of Tor proxy
      # $TOR_PROXY_PORT - Port of Tor proxy
      #
      # App specific environment variables
      # $APP_HIDDEN_SERVICE - The address of the Tor hidden service your app will be exposed at
      # $APP_PASSWORD - Unique plain text password that can be used for authentication in your app, shown to the user in the Umbrel UI
      # $APP_SEED - Unique 256 bit long hex string (128 bits of entropy) deterministically derived from user's Umbrel seed and your app's ID
      
  server:
    image: ghcr.io/sharknoon/pixina-backend:latest@sha256:56d91accbe3efcb9e2d201688d6c1e94ed0da01ca069156cd993f1d4e8602ec2
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data:/app/bin/data
    environment:
      PIXINA_EXCEL_POLL_INTERVAL_MS: 86400000
      PIXINA_EXCEL_POLL_URL: https://api.onedrive.com/v1.0/shares/u%21aHR0cHM6Ly8xZHJ2Lm1zL3gvcyFBcjR2UFFNR01oRGVqYzlaU3dRT2pXTVNaVk9aUVE_ZT1kbVRJclk/root/content
