version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: sharknoon-ntfy_app_1
      APP_PORT: 80
      # If you want to disable the app proxy, you can set this to 'false'
      # Disabling the app proxy will make your app accessible without the Umbrel authentication
      #PROXY_AUTH_ADD: "true"
      # If you only want to allow public access to some parts of the app, you can use white/blacklists Here
      #PROXY_AUTH_WHITELIST: "*"
      #PROXY_AUTH_BLACKLIST: "/admin/*"
  
  app:
    image: binwiederhier/ntfy:v2.11.0@sha256:4a7d0f0adc6d5d9fc36e64ab55ef676e76e124a2bdd50ce115b6d9c1c7430294
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
    command:
      - serve
    volumes:
      - ${APP_DATA_DIR}/data/cache:/var/cache/ntfy
      - ${APP_DATA_DIR}/data/data:/etc/ntfy
    environment:
      NTFY_BASE_URL: http://${DEVICE_DOMAIN_NAME}:${APP_PROXY_PORT}
      NTFY_ENABLE_LOGIN: true
      NTFY_AUTH_FILE: ${APP_DATA_DIR}/data/users.db
      NTFY_AUTH_DEFAULT_ACCESS: deny-all